### ISSUE TITLE
Dashboard Structure 

### ISSUE THREAD

**Issue by Mtduffey36** [Mtduffey36/mood-sync#38]

**Comment by Ejacosta86** [comment]
dashboard will have two drop downs
1-showing the main emotion 
2-showing the sub category emotion 

under the emotion selections will have a text box for the user to be able to free text their emotions

heat calendar will be set under the text box.

**Comment by Ejacosta86** [comment]
Andres processed 
dashboard will have two drop downs
1-showing the main emotion
2-showing the sub category emotion
under the emotion selections will have a text box for the user to be able to free text their emotions
